# Generated by Django 2.1.5 on 2019-02-04 13:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'bank account'), (1, 'credit card'), (2, 'debit card')], db_index=True, default=0, verbose_name='account type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('active', models.BooleanField(default=True, verbose_name='account active')),
            ],
            options={
                'verbose_name': 'bookkeeping account',
                'verbose_name_plural': 'bookkeeping accounts',
            },
        ),
        migrations.CreateModel(
            name='UnidentifiedDepositSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'transaction pending'), (1, 'transaction complete'), (2, 'transaction revoked')], db_index=True, default=0, verbose_name='slip status')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='transaction amount')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('remarks', models.TextField(blank=True, verbose_name='slip remarks')),
                ('type', models.IntegerField(choices=[(0, 'unidentified'), (1, 'identified'), (2, 'overdrawn deposit')], db_index=True, default=0, verbose_name='deposit type')),
                ('completed', models.DateTimeField(null=True, verbose_name='completed date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_deposits', to='bookkeeping.Account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'unidentified deposit slip',
                'verbose_name_plural': 'unidentified deposit slips',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'transaction pending'), (1, 'transaction complete'), (2, 'transaction revoked')], db_index=True, default=0, verbose_name='slip status')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='transaction amount')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('remarks', models.TextField(blank=True, verbose_name='slip remarks')),
                ('type', models.IntegerField(choices=[(0, 'purchase'), (1, 'refund'), (2, 'refund overdrawn'), (3, 'expense'), (4, 'salary')], db_index=True, default=0, verbose_name='withdrawal type')),
                ('completed', models.DateTimeField(null=True, verbose_name='completed date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='bookkeeping.Account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'withdrawal slip',
                'verbose_name_plural': 'withdrawal slips',
            },
        ),
    ]
