# Generated by Django 2.2.2 on 2019-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_emailbanned_phonebanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebanned',
            name='phone',
            field=models.CharField(default='01012341234', max_length=16, verbose_name='phone number'),
        ),
    ]
