# Generated by Django 2.2.2 on 2019-06-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190614_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailbanned',
            options={'verbose_name': 'Banned Email Address', 'verbose_name_plural': 'Banned Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='phonebanned',
            options={'verbose_name': 'Banned Phone Numbers', 'verbose_name_plural': 'Banned Phone Numbers'},
        ),
    ]
