# Generated by Django 2.2.2 on 2019-06-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20190616_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebanned',
            options={'verbose_name': 'Banned Phone Number', 'verbose_name_plural': 'Banned Phone Numbers'},
        ),
    ]
