# Generated by Django 2.2.13 on 2020-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='stock quantity'),
        ),
    ]
