# Generated by Django 2.2.1 on 2019-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='naver_partner_title_pg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Naver Shopping Partner Zone Product Name (PG)'),
        ),
    ]
