# Generated by Django 2.2.4 on 2019-09-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_stock_level',
            new_name='maximum_stock_level',
        ),
    ]
