# Generated by Django 2.2.1 on 2019-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_naver_partner_title_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count_pg',
            field=models.PositiveIntegerField(default=0, verbose_name='review comment count(PG)'),
        ),
    ]
