# Generated by Django 2.2.24 on 2021-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='signup_open',
            field=models.BooleanField(default=True, verbose_name='signup closed'),
        ),
    ]
