# Generated by Django 2.2.4 on 2019-09-23 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('account', models.IntegerField(choices=[(0, 'KOOKMIN BANK'), (1, 'NONGHYUP BANK'), (2, 'SHINHAN BANK'), (3, 'WOORI BANK'), (4, 'IBK BANK')], db_index=True, default=0, verbose_name='account')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.PurchaseOrder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'purchase order payment',
                'verbose_name_plural': 'purchase order payments',
            },
        ),
    ]
