# Generated by Django 2.2.4 on 2019-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_review_count_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.IntegerField(default=0, verbose_name='maximum stock level'),
        ),
    ]
