# Generated by Django 2.2.4 on 2019-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_purchaseorderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
