# Generated by Django 2.2.4 on 2019-09-24 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_purchaseorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='balance'),
        ),
    ]
