# Generated by Django 3.2.12 on 2022-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_store_under_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Bank Transfer'), (1, 'Escrow (KB)'), (2, 'PayPal'), (3, 'Credit Card'), (4, 'Bank Transfer (PG)'), (5, 'Virtual Account'), (6, 'Phone Bill')], db_index=True, default=0, verbose_name='payment method'),
        ),
    ]
