# Generated by Django 2.1.7 on 2019-02-21 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_id', models.IntegerField(verbose_name='site id')),
                ('analytics_uid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Google Analytics UA-ID')),
            ],
            options={
                'verbose_name': 'Google Service',
                'verbose_name_plural': 'Google Services',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Site menu item title. Can contain template variables E.g.: {{ mytitle }}', max_length=255, verbose_name='title')),
                ('url', models.CharField(db_index=True, help_text='Exact URL or URL pattern', max_length=255, verbose_name='url')),
                ('match', models.IntegerField(choices=[(0, 'equals'), (1, 'startswith')], default=0, verbose_name='match')),
                ('target', models.IntegerField(choices=[(0, '_self'), (1, 'blank')], default=0, verbose_name='target')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rakmai.MenuItem', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
        ),
    ]
