# Generated by Django 2.1.7 on 2019-02-21 08:23

import banner.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('status', models.IntegerField(choices=[(0, 'enabled'), (1, 'disabled')], db_index=True, default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('target', models.IntegerField(choices=[(0, '_self'), (1, 'blank')], default=0, verbose_name='target')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('status', models.IntegerField(choices=[(0, 'visible'), (1, 'hidden')], db_index=True, default=0, verbose_name='status')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=banner.models.upload_directory_path, verbose_name='thumbnail')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='banner.Banner', verbose_name='banner')),
            ],
            options={
                'verbose_name': 'banner item',
                'verbose_name_plural': 'banner items',
            },
        ),
    ]
